### ISSUE TITLE
Searching error with some searching args

### ISSUE THREAD

**Issue by redrussianarmy** [bisoncorps/search-engine-parser#100]
When I try to search on google, the program gives following error with some searching args. I could not specify all of them but I can give some examples of searching args.

('fatih terim kimdir site:tr.wikipedia.org', 0)
('amerikanın yüz ölçümü ne kadardır site:tr.wikipedia.org', 0)
('almanyanın başkenti neresidir site:tr.wikipedia.org', 0)

**Error:**

```
Traceback (most recent call last):
  File "/home/xavier/.local/lib/python3.6/site-packages/search_engine_parser/core/base.py", line 239, in get_results
    search_results = self.parse_result(results, **kwargs)
  File "/home/xavier/.local/lib/python3.6/site-packages/search_engine_parser/core/base.py", line 151, in parse_result
    rdict = self.parse_single_result(each, **kwargs)
  File "/home/xavier/.local/lib/python3.6/site-packages/search_engine_parser/core/engines/google.py", line 49, in parse_single_result
    h3_tag = r_elem.find('h3')
AttributeError: 'NoneType' object has no attribute 'find'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "get_request.py", line 106, in <module>
    print(getrequest.run(keyword))
  File "get_request.py", line 88, in run
    url = SearchOnline().run(keyword)
  File "/home/xavier/projects/Darvis_cpy/darvis/search/../../darvis/search/search_online.py", line 20, in run
    gresults = self.gsearch.search(*search_args, url="https://google.com.tr")
  File "/home/xavier/.local/lib/python3.6/site-packages/search_engine_parser/core/base.py", line 266, in search
    return self.get_results(soup, **kwargs)
  File "/home/xavier/.local/lib/python3.6/site-packages/search_engine_parser/core/base.py", line 243, in get_results
    "The returned results could not be parsed. This might be due to site updates or "
search_engine_parser.core.exceptions.NoResultsOrTrafficError: The returned results could not be parsed. This might be due to site updates or server errors. Drop an issue at https://github.com/bisoncorps/search-engine-parser if this persists
```

**Here is my searching class:**

```
from search_engine_parser.core.engines.google import Search as GoogleSearch

class SearchOnline(metaclass = Singleton):
    def __init__(self):
        self.gsearch = GoogleSearch()
        self.target_url = ""
    def run(self, keyword):
        search_args = ((keyword + ' site:tr.wikipedia.org'), 0)
        print("search args:", search_args)
        gresults = self.gsearch.search(*search_args, url="https://google.com.tr")
        self.target_url = gresults["links"][0]
        print("reached url:", self.target_url)
        return self.target_url  
```

**Desktop:**

OS: Ubuntu 18.04.4 LTS
Python Version: 3.6.9
Search-engine-parser version: 0.6.1

**Comment by deven96** [comment]
Can I ask why you are using page 0 in your search args?

**Comment by redrussianarmy** [comment]
I am using page 0 to reach first page. When I write "1", it directs to second page

**Comment by deven96** [comment]
Has using 0 ever worked for you?

**Comment by redrussianarmy** [comment]
It generally works with 0. I realized that after version 0.6.1. However, sometimes I get an error that I have mentioned

**Comment by deven96** [comment]
I'd look into this thanks

**Comment by deven96** [comment]
Please @redrussianarmy test if the latest code on master fixes your issue
