### ISSUE TITLE
[Bug report] pysearch tool broken

### ISSUE THREAD

**Issue by chris4540** [bisoncorps/search-engine-parser#109]
**Describe the bug**
After installing the `pysearch` cli tool and try to use it, the tool reports error:
ImportError: cannot import name 'runner'

**To Reproduce**
```bash
mkvirtualenv search_engine_parser
pip install "search-engine-parser[cli]"
pysearch --help
```
```python
Traceback (most recent call last):
  File "/home/chrislin/.virtualenvs/search_engine_parser/bin/pysearch", line 5, in <module>
    from search_engine_parser.core.cli import runner
ImportError: cannot import name 'runner'

```
**Expected behavior**
Show help message from pysearch

**Screenshots**
![image](https://user-images.githubusercontent.com/12794588/91631275-c07f5700-e9d8-11ea-990a-6461afaeb938.png)

**Desktop (please complete the following information):**
 - OS: WSL2 Ubuntu 18.04
 - Python Version Python 3.6.9
 - Search-engine-parser version 0.6.1

**Additional context**
Cause:
The runner function was removed.

Solution:
Either add back runner in search_engine_parser.core.cli or change the entry_points in setup.py

Related pull request:
https://github.com/bisoncorps/search-engine-parser/pull/108

**Comment by 07416** [comment]
Is this still an issue? When running `pysearch --help`:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2451, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'search_engine_parser.core.cli' has no attribute 'runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/bin/pysearch", line 11, in <module>
    load_entry_point('search-engine-parser==0.6.1', 'console_scripts', 'pysearch')()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2453, in resolve
    raise ImportError(str(exc))
ImportError: module 'search_engine_parser.core.cli' has no attribute 'runner'
```

**Comment by MeNsaaH** [comment]
For now you can install  using  `pip install git+https://github.com/bisoncorps/search-engine-parser`. the fix is in future version to be deployed on pypi
