### ISSUE TITLE
Google parser broken.

### ISSUE THREAD

**Issue by AvinashReddy3108** [bisoncorps/search-engine-parser#114]
**Describe the bug**
The library fails to parse Google search results, probably because of changes by Google.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install the library via pip (using `pip install search-engine-parser`)
2. Save [this snippet](https://github.com/bisoncorps/search-engine-parser#code) as a file. (I saved it as `search.py`)
3. Run the snippet as script. (using `python3 search.py`)
4. See error.

**Expected behaviour**
It should show the search results, as formatted by the snippet.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Arch Linux x86_64 
 - Python Version: 3.8.5
 - Search-engine-parser version: 0.6.1

**Additional context**
Here's the error log to help with debugging.

```
[avinash@rustbucket ~]$ python search.py

https://www.google.com/search?num=10&start=1&q=preaching+to+the+choir&client=ubuntu True
Traceback (most recent call last):
  File "/home/avinash/PPRPLNRMX/lib/python3.8/site-packages/search_engine_parser/core/base.py", line 239, in get_results
    search_results = self.parse_result(results, **kwargs)
  File "/home/avinash/PPRPLNRMX/lib/python3.8/site-packages/search_engine_parser/core/base.py", line 151, in parse_result
    rdict = self.parse_single_result(each, **kwargs)
  File "/home/avinash/PPRPLNRMX/lib/python3.8/site-packages/search_engine_parser/core/engines/google.py", line 49, in parse_single_result
    h3_tag = r_elem.find('h3')
AttributeError: 'NoneType' object has no attribute 'find'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "search.py", line 11, in <module>
    gresults = gsearch.search(*search_args)
  File "/home/avinash/PPRPLNRMX/lib/python3.8/site-packages/search_engine_parser/core/base.py", line 266, in search
    return self.get_results(soup, **kwargs)
  File "/home/avinash/PPRPLNRMX/lib/python3.8/site-packages/search_engine_parser/core/base.py", line 242, in get_results
    raise NoResultsOrTrafficError(
search_engine_parser.core.exceptions.NoResultsOrTrafficError: The returned results could not be parsed. This might be due to site updates or server errors. Drop an issue at https://github.com/bisoncorps/search-engine-parser if this persists
```

**Comment by MlataIbrahim** [comment]
I have the same issue :/

**Comment by deven96** [comment]
Could you please confirm if this is happening with an installation directly from master? @AvinashReddy3108

**Comment by AvinashReddy3108** [comment]
> Could you please confirm if this is happening with an installation directly from master? @AvinashReddy3108

- Installing directly from master.
```
Collecting git+https://github.com/bisoncorps/search-engine-parser
  Cloning https://github.com/bisoncorps/search-engine-parser to /tmp/pip-req-build-dbld7lrf
Requirement already satisfied: lxml==4.5.2 in ./PPRPLNRMX/lib/python3.8/site-packages (from search-engine-parser==0.6.1) (4.5.2)
Requirement already satisfied: aiohttp==3.6.2 in ./PPRPLNRMX/lib/python3.8/site-packages (from search-engine-parser==0.6.1) (3.6.2)
Requirement already satisfied: beautifulsoup4==4.9.1 in ./PPRPLNRMX/lib/python3.8/site-packages (from search-engine-parser==0.6.1) (4.9.1)
Requirement already satisfied: async-timeout<4.0,>=3.0 in ./PPRPLNRMX/lib/python3.8/site-packages (from aiohttp==3.6.2->search-engine-parser==0.6.1) (3.0.1)
Requirement already satisfied: yarl<2.0,>=1.0 in ./PPRPLNRMX/lib/python3.8/site-packages (from aiohttp==3.6.2->search-engine-parser==0.6.1) (1.5.1)
Requirement already satisfied: attrs>=17.3.0 in ./PPRPLNRMX/lib/python3.8/site-packages (from aiohttp==3.6.2->search-engine-parser==0.6.1) (20.2.0)
Requirement already satisfied: multidict<5.0,>=4.5 in ./PPRPLNRMX/lib/python3.8/site-packages (from aiohttp==3.6.2->search-engine-parser==0.6.1) (4.7.6)
Requirement already satisfied: chardet<4.0,>=2.0 in ./PPRPLNRMX/lib/python3.8/site-packages (from aiohttp==3.6.2->search-engine-parser==0.6.1) (3.0.4)
Requirement already satisfied: soupsieve>1.2 in ./PPRPLNRMX/lib/python3.8/site-packages (from beautifulsoup4==4.9.1->search-engine-parser==0.6.1) (2.0.1)
Requirement already satisfied: idna>=2.0 in ./PPRPLNRMX/lib/python3.8/site-packages (from yarl<2.0,>=1.0->aiohttp==3.6.2->search-engine-parser==0.6.1) (2.10)
Building wheels for collected packages: search-engine-parser
  Building wheel for search-engine-parser (setup.py): started
  Building wheel for search-engine-parser (setup.py): finished with status 'done'
  Created wheel for search-engine-parser: filename=search_engine_parser-0.6.1-py3-none-any.whl size=36848 sha256=208bcc2c097980e1e0abed97aa3610afe1d40c494e16c43257bda8a3e9a3d0e3
  Stored in directory: /tmp/pip-ephem-wheel-cache-j9yt_aot/wheels/ef/af/cf/6287075a4eb17704ce6130a271e8dc48caf78cebe51223d3c8
Successfully built search-engine-parser
Installing collected packages: search-engine-parser
Successfully installed search-engine-parser-0.6.1
```

- Code snippet used for testing said engine.
```python
import pprint
from search_engine_parser.core.engines.google import Search as GoogleSearch

search_args = ('AvinashReddy3108', 1)
gsearch = GoogleSearch()
gresults = gsearch.search(*search_args)

a = {"Google": gresults}

# pretty print the result from each engine
for k, v in a.items():
    print(f"-------------{k}------------")
    for result in v:
        pprint.pprint(result)

# print first title from google search
print(gresults["titles"][0])

# print first result containing links, descriptions and title
print(gresults[0])

```
- Test results
```
-------------Google------------
{'descriptions': 'Just another script kid, kangs code for fun. '
                 'AvinashReddy3108 has 13 repositories available. Follow their '
                 'code on GitHub.AvinashReddy3108 ...Avinash '
                 'ReddyLitMuxYetAnotherSMSBomberAvinash Reddy ...README.md',
 'links': 'https://www.google.com/url?q=https://github.com/AvinashReddy3108&sa=U&ved=2ahUKEwimiJagq53sAhXGxFkKHVkiASsQFjAAegQIBxAB&usg=AOvVaw1bMKSx6oNvJdePfvg6m16M',
 'titles': 'AvinashReddy3108 (Avinash Reddy) - GitHub'}
{'descriptions': 'Avinash Reddy // Script Gangsta. @AvinashReddy3108. ⛓: '
                 '@\u200baustinhornhead_12 // : @MemezByAvinashReddy · Send '
                 'Message. If you have Telegram, you\xa0...',
 'links': 'https://www.google.com/url?q=https://t.me/AvinashReddy3108&sa=U&ved=2ahUKEwimiJagq53sAhXGxFkKHVkiASsQFjAHegQIBhAB&usg=AOvVaw0zta9TyfN5YiZKreAr_4DM',
 'titles': 'Contact @AvinashReddy3108 - Telegram'}
{'descriptions': 'Ravindra Reddy Ippala · CV Reddy · Reddy Krishna. Contact '
                 'Information. Websites. http://energized.pro/. Facebook. '
                 'http://facebook.com/\u200bAvinashReddy3108.',
 'links': 'https://www.google.com/url?q=https://www.facebook.com/AvinashReddy3108&sa=U&ved=2ahUKEwimiJagq53sAhXGxFkKHVkiASsQFjAIegQIBBAB&usg=AOvVaw23m37lL1HDpynGGfUibFo1',
 'titles': 'Avinash Reddy | Facebook'}
{'descriptions': 'The u/AvinashReddy3108 community on Reddit. Reddit gives you '
                 'the best of the internet in one place.',
 'links': 'https://www.google.com/url?q=https://www.reddit.com/user/AvinashReddy3108/&sa=U&ved=2ahUKEwimiJagq53sAhXGxFkKHVkiASsQFjAJegQIARAB&usg=AOvVaw3qRKhdU6PGt7XMygKHuPuT',
 'titles': 'overview for AvinashReddy3108 - Reddit'}
{'descriptions': '53 Followers, 53 Following, 0 Posts - See Instagram photos '
                 'and videos from Avinash Reddy // LoneWolf ™️ '
                 '(@avinashreddy3108)',
 'links': 'https://www.google.com/url?q=https://www.instagram.com/avinashreddy3108/&sa=U&ved=2ahUKEwimiJagq53sAhXGxFkKHVkiASsQFjAKegQIAhAB&usg=AOvVaw0iPUA6Ei2peOv8iJYqYFDB',
 'titles': 'Avinash Reddy // LoneWolf ™️ (@avinashreddy3108) • Instagram ...'}
{'descriptions': 'Telegram User Bot. by AvinashReddy3108. GitHub Readme.md. '
                 'Project Paperplane Extended. [Project is dead, use '
                 'Friendly-Telegram instead.] A modular\xa0...',
 'links': 'https://www.google.com/url?q=https://elements.heroku.com/buttons/AvinashReddy3108/PaperplaneExtended&sa=U&ved=2ahUKEwimiJagq53sAhXGxFkKHVkiASsQFjALegQIBRAB&usg=AOvVaw1cWc4d3jNs5i-3hbcsoHbg',
 'titles': 'AvinashReddy3108/PaperplaneExtended - Buttons - Heroku Elements'}
{'descriptions': 'PaperplaneRemix. by AvinashReddy3108. GitHub Readme.md. '
                 'Project Paperplane Remix. Such borked, much kanged, very '
                 'meme. Status GitHub issues\xa0...',
 'links': 'https://www.google.com/url?q=https://elements.heroku.com/buttons/AvinashReddy3108/PaperplaneRemix&sa=U&ved=2ahUKEwimiJagq53sAhXGxFkKHVkiASsQFjAMegQIAxAB&usg=AOvVaw162y-NVazsyuUqeHbgU9Na',
 'titles': 'AvinashReddy3108/PaperplaneRemix - Buttons - Heroku Elements'}
AvinashReddy3108 (Avinash Reddy) - GitHub
{'titles': 'AvinashReddy3108 (Avinash Reddy) - GitHub', 'links': 'https://www.google.com/url?q=https://github.com/AvinashReddy3108&sa=U&ved=2ahUKEwimiJagq53sAhXGxFkKHVkiASsQFjAAegQIBxAB&usg=AOvVaw1bMKSx6oNvJdePfvg6m16M', 'descriptions': 'Just another script kid, kangs code for fun. AvinashReddy3108 has 13 repositories available. Follow their code on GitHub.AvinashReddy3108 ...Avinash ReddyLitMuxYetAnotherSMSBomberAvinash Reddy ...README.md'}
```

I can confirm that this works fine. :smile:

**Comment by deven96** [comment]
Okay then. I will prep a new release but for now, anyone with the issue can install from master

**Comment by 07416** [comment]
I receive this error when parsing links:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2451, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'search_engine_parser.core.cli' has no attribute 'runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/bin/pysearch", line 11, in <module>
    load_entry_point('search-engine-parser==0.6.1', 'console_scripts', 'pysearch')()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2453, in resolve
    raise ImportError(str(exc))
ImportError: module 'search_engine_parser.core.cli' has no attribute 'runner'
```

**Comment by AvinashReddy3108** [comment]
> Okay then. I will prep a new release but for now, anyone with the issue can install from master

Feel free to close this when you do. :smile:
