### ISSUE TITLE
Some Error 

### ISSUE THREAD

**Issue by 1Danish-00** [bisoncorps/search-engine-parser#133]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/search_engine_parser/core/base.py", line 239, in get_results
  File "/usr/local/lib/python3.9/site-packages/search_engine_parser/core/base.py", line 151, in parse_result
    if not self._parsed_url:
  File "/usr/local/lib/python3.9/site-packages/search_engine_parser/core/engines/google.py", line 49, in parse_single_result
    h3_tag = r_elem.find('h3')
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by deven96** [comment]
Please provide some more context concerning this? @1Danish-00
