### ISSUE TITLE
GitHub Search Bug

### ISSUE THREAD

**Issue by AbirHasan2005** [bisoncorps/search-engine-parser#136]
There is a bug with GitHub Search:
```
2021-03-08T19:21:07.883082+00:00 app[worker.1]: Traceback (most recent call last):
2021-03-08T19:21:07.883082+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/search_engine_parser/core/base.py", line 240, in get_results
2021-03-08T19:21:07.883083+00:00 app[worker.1]: search_results = self.parse_result(results, **kwargs)
2021-03-08T19:21:07.883083+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/search_engine_parser/core/base.py", line 151, in parse_result
2021-03-08T19:21:07.883084+00:00 app[worker.1]: rdict = self.parse_single_result(each, **kwargs)
2021-03-08T19:21:07.883084+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/search_engine_parser/core/engines/github.py", line 94, in parse_single_result
2021-03-08T19:21:07.883085+00:00 app[worker.1]: rdict["descriptions"] = desc.text
2021-03-08T19:21:07.883085+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'text'
2021-03-08T19:21:07.883086+00:00 app[worker.1]:
2021-03-08T19:21:07.883087+00:00 app[worker.1]: During handling of the above exception, another exception occurred:
2021-03-08T19:21:07.883087+00:00 app[worker.1]:
2021-03-08T19:21:07.883087+00:00 app[worker.1]: Traceback (most recent call last):
2021-03-08T19:21:07.883089+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
2021-03-08T19:21:07.883089+00:00 app[worker.1]: await handler.callback(self.client, *args)
2021-03-08T19:21:07.883090+00:00 app[worker.1]: File "/app/plugins/inline.py", line 107, in answer
2021-03-08T19:21:07.883090+00:00 app[worker.1]: gitresults = await github.async_search(gitsearch)
2021-03-08T19:21:07.883090+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/search_engine_parser/core/base.py", line 286, in async_search
2021-03-08T19:21:07.883091+00:00 app[worker.1]: return self.get_results(soup, **kwargs)
2021-03-08T19:21:07.883091+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/search_engine_parser/core/base.py", line 243, in get_results
2021-03-08T19:21:07.883092+00:00 app[worker.1]: raise NoResultsOrTrafficError(
2021-03-08T19:21:07.883093+00:00 app[worker.1]: search_engine_parser.core.exceptions.NoResultsOrTrafficError: The returned results could not be parsed. This might be due to site updates or server errors. Drop an issue at https://github.com/bisoncorps/search-engine-parser if this persists
```

**Comment by AbirHasan2005** [comment]
Thanks Sir ❤️
