### ISSUE TITLE
ModuleNotFound error with CLI tool.

### ISSUE THREAD

**Issue by AvinashReddy3108** [bisoncorps/search-engine-parser#68]
**Describe the bug**
Could not search using `pysearch` CLI tool

**To Reproduce**
1. Open Termux/Terminal, upgrade the packages using `apt upgrade -y`
2. Install Python3 using `apt install python`
3. Install lxml requirements in Termux using `apt install clang libxslt libxml2 libxml2-utils` and then use `pip install search-engine-parser` to install the package.
4. Run `pysearch --engine bing search --query "Preaching to the choir" --type descriptions` from docs, to test.
5. See error.

**Expected behavior**
As shown in the example gif in the README, it should return search results.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: Android 7.1.2 (LineageOS 14.1) - using [Termux](https://play.google.com/store/apps/details?id=com.termux) app, Python 3.7.4
- OS: Linux Mint 19.2 Tina (based on Ubuntu 18.04 Bionic LTS), Python 3.6.8
 - Search-engine-parser version: 0.5.3.post3 (on both systems).

**Additional context**
Here's the traceback data which may help to solve the issue.
```
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/pysearch", line 11, in <module>
    load_entry_point('search-engine-parser==0.5.3.post3', 'console_scripts', 'pysearch')()                                                                                       
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point                                                    
    return get_distribution(dist).load_entry_point(group, name)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()                                                                                                                                                             
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()                                                                                                                                                        
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/search_engine_parser/core/cli.py", line 7, in <module>
    from blessed import Terminal
ModuleNotFoundError: No module named 'blessed'
```

**Comment by deven96** [comment]
I'm not certain but it seems this is because we split the cli dependencies from library dependencies. Try pip install "search-engine-parser[cli]"
